### ISSUE TITLE
Can't get plugin to connect to Docker

### ISSUE THREAD

**Issue by Zeldapedia** [offsecginger/CTFd-Docker-Challenges#28]
I've been trying to get the plugin to connect to my server's port 2376 using HTTPS for a few days now, but I keep getting the error from the picture below. I know that the Docker service I have running (on the same machine BTW) is working because I can use **"docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem -H=ballisticctf.org:2376 version"** and it will output the version. I have tried every IP address and I still get the same issues. The CTFd instance we have running is containerized, if that makes any difference
![CTFdPluginIssue1](https://user-images.githubusercontent.com/70828383/229636162-632bae7e-d828-46f8-86e3-026d33f84154.png)
![CTFdPluginIssue2](https://user-images.githubusercontent.com/70828383/229636173-64f52e6c-6ce2-42d0-8b39-130dda68bd74.png)

**Comment by SemyonHoyrish** [comment]
I had the same problem.
The way I solved it:
Replace line 285 (`result = r.json()['ContainerConfig']['ExposedPorts'].keys()`)
to `result = r.json()['Config']['ExposedPorts'].keys()`

I suppose the Docket API changed from the time this plugin was written.

**Comment by Zeldapedia** [comment]
Unfortunately, this didn't change anything. Is your CTFd instance containerized? If so, did you create a separate Docker daemon process to manage the containers for this plugin? That is what I did, but maybe I am overthinking it

**Comment by SemyonHoyrish** [comment]
Yes, my CTFd instance running via `docker compose`.
No, I did not create a separate Docker daemon.

Does user, that running CTFd can run docker commands without `sudo`?

**Comment by SemyonHoyrish** [comment]
If we go through configuration this on fresh installation of the server (Ubuntu 22.04, for example):

- Installing docker [official docs](https://docs.docker.com/engine/install/ubuntu/)
- Allow run docker without `sudo` [official post-install guide](https://docs.docker.com/engine/install/linux-postinstall/)
- cloning repos
- changing `__init__.py` for plugin, as mentioned above.

I also need next steps to make it's working:
- `sudo systemctl stop docker`
- `sudo dockerd -H unix:///var/run/docker.sock -H tcp://192.168.0.116:2375`

Then `docker compose up` in the CTFd directory, and it's working!

**Comment by Zeldapedia** [comment]
Is 192.168.0.116 supposed to be the IP address of the CTF server itself? Or the local IP of the Docker container running the CTFd instance?

**Comment by SemyonHoyrish** [comment]
I used the public ip address of the server.

**Comment by Zeldapedia** [comment]
After reviewing my setup, I believe three things were at fault here:

1. my dockerd process wasn't listening at both -H unix:///var/run/docker.sock _and_ -H tcp://<domain IP>:2376
2. the original line 285 in __init__.py
3. my firewall wasn't allowing data through from the IP address of my CTFd container 

After fixing all three of these items, I can now get the regular, unencrypted connections to work! However, I still get the same error when attempting to connect via HTTPS. I even regenerated all my certs, so I do not know what the issue could be there. However, I think I am fine with this for now. So long as my firewall only allows the local IP address through that port, I do not believe this to be a security issue. Thank you for helping!
