### ISSUE TITLE
Stuck on loading repositories

### ISSUE THREAD

**Issue by Void2g** [offsecginger/CTFd-Docker-Challenges#9]
Hey, I am trying to use this plugin but i am stuck loading repositories.

![Admin Panel](https://user-images.githubusercontent.com/44909180/130320441-eccea9e5-06ce-449f-9162-8c72e8aa9ba0.png)

I am running the docker daemon with `sudo dockerd --tls=false -H=127.0.0.1:2376`. When trying to access the images by the browser everything seems to work as it should.

![imagesthrough browser](https://user-images.githubusercontent.com/44909180/130320469-097b893a-9015-4d5d-992e-d9a781ab3da5.png)

I am not able to figure out what is going wrong for me here. This are the messages I receive when entering the address into the admin panel:

<pre><font color="#C4A000">ctfd_1   |</font> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host=&apos;127.0.0.1&apos;, port=2376): Max retries exceeded with url: /images/json?all=1 (Caused by NewConnectionError(&apos;&lt;urllib3.connection.HTTPConnection object at 0x7f6dac494a90&gt;: Failed to establish a new connection: [Errno 111] Connection refused&apos;))
<font color="#C4A000">ctfd_1   |</font> 
<font color="#C4A000">ctfd_1   |</font> During handling of the above exception, another exception occurred:
<font color="#C4A000">ctfd_1   |</font> 
<font color="#C4A000">ctfd_1   |</font> Traceback (most recent call last):
<font color="#C4A000">ctfd_1   |</font>   File &quot;/opt/CTFd/CTFd/plugins/docker_challenges/__init__.py&quot;, line 226, in do_request
<font color="#C4A000">ctfd_1   |</font>     r = requests.get(url=f&quot;%s{url}&quot; % URL_TEMPLATE, headers=headers)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/requests/api.py&quot;, line 76, in get
<font color="#C4A000">ctfd_1   |</font>     return request(&apos;get&apos;, url, params=params, **kwargs)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/requests/api.py&quot;, line 61, in request
<font color="#C4A000">ctfd_1   |</font>     return session.request(method=method, url=url, **kwargs)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/requests/sessions.py&quot;, line 530, in request
<font color="#C4A000">ctfd_1   |</font>     resp = self.send(prep, **send_kwargs)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/requests/sessions.py&quot;, line 643, in send
<font color="#C4A000">ctfd_1   |</font>     r = adapter.send(request, **kwargs)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/requests/adapters.py&quot;, line 516, in send
<font color="#C4A000">ctfd_1   |</font>     raise ConnectionError(e, request=request)
<font color="#C4A000">ctfd_1   |</font> requests.exceptions.ConnectionError: HTTPConnectionPool(host=&apos;127.0.0.1&apos;, port=2376): Max retries exceeded with url: /images/json?all=1 (Caused by NewConnectionError(&apos;&lt;urllib3.connection.HTTPConnection object at 0x7f6dac494a90&gt;: Failed to establish a new connection: [Errno 111] Connection refused&apos;))
<font color="#C4A000">ctfd_1   |</font> Traceback (most recent call last):
<font color="#C4A000">ctfd_1   |</font>   File &quot;/opt/CTFd/CTFd/plugins/docker_challenges/__init__.py&quot;, line 143, in docker_config
<font color="#C4A000">ctfd_1   |</font>     repos = get_repositories(docker)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/opt/CTFd/CTFd/plugins/docker_challenges/__init__.py&quot;, line 260, in get_repositories
<font color="#C4A000">ctfd_1   |</font>     for i in r.json():
<font color="#C4A000">ctfd_1   |</font> AttributeError: &apos;list&apos; object has no attribute &apos;json&apos;
<font color="#C4A000">ctfd_1   |</font> Traceback (most recent call last):
<font color="#C4A000">ctfd_1   |</font>   File &quot;/opt/CTFd/CTFd/plugins/docker_challenges/__init__.py&quot;, line 107, in docker_config
<font color="#C4A000">ctfd_1   |</font>     ca_cert = request.files[&apos;ca_cert&apos;].stream.read()
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/werkzeug/datastructures.py&quot;, line 442, in __getitem__
<font color="#C4A000">ctfd_1   |</font>     raise exceptions.BadRequestKeyError(key)
<font color="#C4A000">ctfd_1   |</font> werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
<font color="#C4A000">ctfd_1   |</font> Traceback (most recent call last):
<font color="#C4A000">ctfd_1   |</font>   File &quot;/opt/CTFd/CTFd/plugins/docker_challenges/__init__.py&quot;, line 112, in docker_config
<font color="#C4A000">ctfd_1   |</font>     client_cert = request.files[&apos;client_cert&apos;].stream.read()
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/werkzeug/datastructures.py&quot;, line 442, in __getitem__
<font color="#C4A000">ctfd_1   |</font>     raise exceptions.BadRequestKeyError(key)
<font color="#C4A000">ctfd_1   |</font> werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
<font color="#C4A000">ctfd_1   |</font> Traceback (most recent call last):
<font color="#C4A000">ctfd_1   |</font>   File &quot;/opt/CTFd/CTFd/plugins/docker_challenges/__init__.py&quot;, line 117, in docker_config
<font color="#C4A000">ctfd_1   |</font>     client_key = request.files[&apos;client_key&apos;].stream.read()
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/werkzeug/datastructures.py&quot;, line 442, in __getitem__
<font color="#C4A000">ctfd_1   |</font>     raise exceptions.BadRequestKeyError(key)
<font color="#C4A000">ctfd_1   |</font> werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
<font color="#C4A000">ctfd_1   |</font> Traceback (most recent call last):
<font color="#C4A000">ctfd_1   |</font>   File &quot;/opt/CTFd/CTFd/plugins/docker_challenges/__init__.py&quot;, line 135, in docker_config
<font color="#C4A000">ctfd_1   |</font>     b.repositories = &apos;,&apos;.join(request.form.to_dict(flat=False)[&apos;repositories&apos;])
<font color="#C4A000">ctfd_1   |</font> KeyError: &apos;repositories&apos;
<font color="#C4A000">ctfd_1   |</font> Traceback (most recent call last):
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/urllib3/connection.py&quot;, line 160, in _new_conn
<font color="#C4A000">ctfd_1   |</font>     (self._dns_host, self.port), self.timeout, **extra_kw
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py&quot;, line 84, in create_connection
<font color="#C4A000">ctfd_1   |</font>     raise err
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py&quot;, line 74, in create_connection
<font color="#C4A000">ctfd_1   |</font>     sock.connect(sa)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/gevent/_socket3.py&quot;, line 407, in connect
<font color="#C4A000">ctfd_1   |</font>     raise error(err, strerror(err))
<font color="#C4A000">ctfd_1   |</font> ConnectionRefusedError: [Errno 111] Connection refused
<font color="#C4A000">ctfd_1   |</font> 
<font color="#C4A000">ctfd_1   |</font> During handling of the above exception, another exception occurred:
<font color="#C4A000">ctfd_1   |</font> 
<font color="#C4A000">ctfd_1   |</font> Traceback (most recent call last):
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py&quot;, line 677, in urlopen
<font color="#C4A000">ctfd_1   |</font>     chunked=chunked,
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py&quot;, line 392, in _make_request
<font color="#C4A000">ctfd_1   |</font>     conn.request(method, url, **httplib_request_kw)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/http/client.py&quot;, line 1281, in request
<font color="#C4A000">ctfd_1   |</font>     self._send_request(method, url, body, headers, encode_chunked)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/http/client.py&quot;, line 1327, in _send_request
<font color="#C4A000">ctfd_1   |</font>     self.endheaders(body, encode_chunked=encode_chunked)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/http/client.py&quot;, line 1276, in endheaders
<font color="#C4A000">ctfd_1   |</font>     self._send_output(message_body, encode_chunked=encode_chunked)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/http/client.py&quot;, line 1036, in _send_output
<font color="#C4A000">ctfd_1   |</font>     self.send(msg)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/http/client.py&quot;, line 976, in send
<font color="#C4A000">ctfd_1   |</font>     self.connect()
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/urllib3/connection.py&quot;, line 187, in connect
<font color="#C4A000">ctfd_1   |</font>     conn = self._new_conn()
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/urllib3/connection.py&quot;, line 172, in _new_conn
<font color="#C4A000">ctfd_1   |</font>     self, &quot;Failed to establish a new connection: %s&quot; % e
<font color="#C4A000">ctfd_1   |</font> urllib3.exceptions.NewConnectionError: &lt;urllib3.connection.HTTPConnection object at 0x7f6dac490790&gt;: Failed to establish a new connection: [Errno 111] Connection refused
<font color="#C4A000">ctfd_1   |</font> 
<font color="#C4A000">ctfd_1   |</font> During handling of the above exception, another exception occurred:
<font color="#C4A000">ctfd_1   |</font> 
<font color="#C4A000">ctfd_1   |</font> Traceback (most recent call last):
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/requests/adapters.py&quot;, line 449, in send
<font color="#C4A000">ctfd_1   |</font>     timeout=timeout
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py&quot;, line 727, in urlopen
<font color="#C4A000">ctfd_1   |</font>     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py&quot;, line 446, in increment
<font color="#C4A000">ctfd_1   |</font>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
<font color="#C4A000">ctfd_1   |</font> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host=&apos;127.0.0.1&apos;, port=2376): Max retries exceeded with url: /images/json?all=1 (Caused by NewConnectionError(&apos;&lt;urllib3.connection.HTTPConnection object at 0x7f6dac490790&gt;: Failed to establish a new connection: [Errno 111] Connection refused&apos;))
<font color="#C4A000">ctfd_1   |</font> 
<font color="#C4A000">ctfd_1   |</font> During handling of the above exception, another exception occurred:
<font color="#C4A000">ctfd_1   |</font> 
<font color="#C4A000">ctfd_1   |</font> Traceback (most recent call last):
<font color="#C4A000">ctfd_1   |</font>   File &quot;/opt/CTFd/CTFd/plugins/docker_challenges/__init__.py&quot;, line 226, in do_request
<font color="#C4A000">ctfd_1   |</font>     r = requests.get(url=f&quot;%s{url}&quot; % URL_TEMPLATE, headers=headers)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/requests/api.py&quot;, line 76, in get
<font color="#C4A000">ctfd_1   |</font>     return request(&apos;get&apos;, url, params=params, **kwargs)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/requests/api.py&quot;, line 61, in request
<font color="#C4A000">ctfd_1   |</font>     return session.request(method=method, url=url, **kwargs)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/requests/sessions.py&quot;, line 530, in request
<font color="#C4A000">ctfd_1   |</font>     resp = self.send(prep, **send_kwargs)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/requests/sessions.py&quot;, line 643, in send
<font color="#C4A000">ctfd_1   |</font>     r = adapter.send(request, **kwargs)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/requests/adapters.py&quot;, line 516, in send
<font color="#C4A000">ctfd_1   |</font>     raise ConnectionError(e, request=request)
<font color="#C4A000">ctfd_1   |</font> requests.exceptions.ConnectionError: HTTPConnectionPool(host=&apos;127.0.0.1&apos;, port=2376): Max retries exceeded with url: /images/json?all=1 (Caused by NewConnectionError(&apos;&lt;urllib3.connection.HTTPConnection object at 0x7f6dac490790&gt;: Failed to establish a new connection: [Errno 111] Connection refused&apos;))
<font color="#C4A000">ctfd_1   |</font> Traceback (most recent call last):
<font color="#C4A000">ctfd_1   |</font>   File &quot;/opt/CTFd/CTFd/plugins/docker_challenges/__init__.py&quot;, line 143, in docker_config
<font color="#C4A000">ctfd_1   |</font>     repos = get_repositories(docker)
<font color="#C4A000">ctfd_1   |</font>   File &quot;/opt/CTFd/CTFd/plugins/docker_challenges/__init__.py&quot;, line 260, in get_repositories
<font color="#C4A000">ctfd_1   |</font>     for i in r.json():
<font color="#C4A000">ctfd_1   |</font> AttributeError: &apos;list&apos; object has no attribute &apos;json&apos;
<font color="#C4A000">ctfd_1   |</font> Traceback (most recent call last):
<font color="#C4A000">ctfd_1   |</font>   File &quot;/opt/CTFd/CTFd/plugins/docker_challenges/__init__.py&quot;, line 107, in docker_config
<font color="#C4A000">ctfd_1   |</font>     ca_cert = request.files[&apos;ca_cert&apos;].stream.read()
<font color="#C4A000">ctfd_1   |</font>   File &quot;/usr/local/lib/python3.7/site-packages/werkzeug/datastructures.py&quot;, line 442, in __getitem__
<font color="#C4A000">ctfd_1   |</font>     raise exceptions.BadRequestKeyError(key)
<font color="#C4A000">ctfd_1   |</font> None
<font color="#C4A000">ctfd_1   |</font> None
<font color="#C4A000">ctfd_1   |</font> None
<font color="#C4A000">ctfd_1   |</font> None
<font color="#C4A000">ctfd_1   |</font> None
<font color="#C4A000">ctfd_1   |</font> None
<font color="#C4A000">ctfd_1   |</font> 172.21.0.1 - - [21/Aug/2021:11:42:50 +0000] &quot;POST /admin/docker_config HTTP/1.1&quot; 200 8007 &quot;http://localhost:8000/admin/docker_config&quot; &quot;Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36&quot;</pre>

Could you help me please? Has it something to do with "AttributeError: 'list' object has no attribute 'json'"?

**Comment by Morn98** [comment]
Looks like you are using CTFd with docker-compose. Try using the the IP of the docker0 interface as Hostname.
